# Generated by Django 5.2.6 on 2026-03-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeedetails',
            options={'verbose_name': 'Employee Detail', 'verbose_name_plural': 'Employee Details'},
        ),
        migrations.RenameField(
            model_name='employeedetails',
            old_name='department',
            new_name='departments',
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='employment_id',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
