# Generated by Django 5.2.6 on 2026-03-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_employeedetails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='next_of_kin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='next_of_kin_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
