# Generated by Django 5.2.6 on 2026-03-12 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_employeedetails_next_of_kin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.CharField(choices=[('Advanced', 'Advanced'), ('Midlevel', 'Midlevel'), ('Beginner', 'Begineer')], max_length=200)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.employeedetails')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('dept', models.ManyToManyField(blank=True, max_length=200, null=True, to='API.department')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('training_provider', models.CharField(max_length=200)),
                ('training_location', models.CharField(choices=[('ONSITE', 'onsite'), ('REMOTE', 'remote'), ('HYBRID', 'hybrid')], max_length=200)),
                ('duration', models.DurationField()),
                ('start_date', models.DateField()),
                ('training_dept', models.ManyToManyField(blank=True, max_length=200, null=True, to='API.department')),
            ],
        ),
    ]
